# This file is an example of a config for running the evolutionary algorithm (EA)
# You would put this file in a folder where you want the EA to save the results to
save_options:
  save_dir: ~/hpc-share/uvms/preliminary/trial_0b
ea_parameters:
  number_of_generations: 5000
  mutation_probability: 0.1
  crossover_probability: 0.5
  population_size: 50
  trajectory_names:
    - _alt_001-0
    # - _alt_001-1
    # - _alt_001-2
    # - _alt_002-0
    # - _alt_002-1
    # - _alt_008-0
    # - _alt_008-1
    # - _alt_008-2
    # - _alt_009-0
    # - _alt_009-1
    # - _alt_011-0
    # - _alt_011-1
    # - _alt_011-2
  start_with_default_params: True
default_dynamic_params:
  cob_vec_dict:
    vehicle: [0.0074, 0.0, 0.02]
    foamL: [0.0, 0.11, 0.027]  # guess
    foamR: [0.0, -0.11, 0.027] # guess
    shoulder: [-0.001, -0.003, 0.032]
    upperarm: [0.073, 0.0, -0.002]
    elbow: [0.003, 0.001, -0.017]
    wrist: [0.0, 0.0, -0.098]
    jaw: [0.0, 0.0, 0.0]
  buoyancy_mag_dict:
    vehicle: 128.33442000000002 #volume times gravity
    foamL: 8.46
    foamR: 8.86
    shoulder: 0.17605026
    upperarm: 1.9854557100000003
    armbase: 1.97567514
    jaw: 0.19561140000000005
    wrist: 1.5159883500000002
    elbow: 0.24451425000000004
  com_vec_dict:
    vehicle: [0.0, 0.0, 0.0]
    weightCA: [-0.2, 0.165, -0.075]
    weightBL: [-0.0975, 0.1275, -0.1325] # guess
    weightBR: [-0.0975, -0.1275, -0.1325] # guess
    dvl: [-0.1887, 0.0439, -0.0595] # guess
    dvlbracket: [-0.1542, 0.0439, -0.0795] # guess
    armbase: [-0.075, -0.006, -0.003]
    shoulder: [0.005, -0.001, 0.016]
    upperarm: [0.073, 0.0, 0.0]
    elbow: [0.017, -0.026, -0.002]
    wrist: [0.0, 0.0, -0.098]
    jaw: [0.0, 0.0, 0.0]
    jaw_wrt_wrist: [0.0, 0.0, -0.19]
  grav_mag_dict:
    vehicle: 129.1977 # Weight * gravity
    weightCA: 3.24
    weightBL: 1.62
    weightBR: 1.62
    dvl: 0.69
    dvlbracket: 1.01
    armbase: 3.3452100000000002
    shoulder: 1.90314
    upperarm: 4.20849
    elbow: 1.1281500000000002
    jaw: 0.49050000000000005
    wrist: 3.2667300000000004
  drag:
    d_lin_angular: 0.07
    d_nonlin_angular: 1.55
    d_lin_coeffs: [4.03, 6.22, 5.18] # The next 3 coefficients are d_lin_angular
    d_nonlin_coeffs: [18.18, 21.66, 36.99] # The next 3 coefficients are d_nonlin_angular
  link_volumes:
    shoulder: 0.018
    upperarm: 0.203
    elbow: 0.025
    wrist: 0.155
    armbase: 0.202
    jaw: 0.02
  link_masses:
    shoulder: 0.194
    upperarm: 0.429
    elbow: 0.115
    wrist: 0.333
    armbase: 0.341
    jaw: 0.05
  link_drags:
    shoulder: [0.26, 0.26, 0.3]
    upperarm: [0.3, 1.6, 1.6]
    elbow: [0.26, 0.3, 0.26]
    wrist: [1.8, 1.8, 0.3]
    jaw: [.05, .05, .05]
