Pkg.add(Pkg.PackageSpec(;name="CSV", version="0.10.11"))
Pkg.add(Pkg.PackageSpec(;name="CoordinateTransformations", version="0.6.3"))
Pkg.add(Pkg.PackageSpec(;name="DataFrames", version="1.6.1"))
Pkg.add(Pkg.PackageSpec(;name="DataInterpolations", version="4.5.0"))
Pkg.add(Pkg.PackageSpec(;name="DataStructures", version="0.18.15"))
Pkg.add(Pkg.PackageSpec(;name="Distributions", version="0.25.103"))
Pkg.add(Pkg.PackageSpec(;name="GeometryBasics", version="0.4.9"))
Pkg.add(Pkg.PackageSpec(;name="Interpolations", version="0.14.7"))
Pkg.add(Pkg.PackageSpec(;name="JLD", version="0.13.3"))
Pkg.add(Pkg.PackageSpec(;name="MechanismGeometries", version="0.7.1"))
Pkg.add(Pkg.PackageSpec(;name="MeshCat", version="0.14.2"))
Pkg.add(Pkg.PackageSpec(;name="MeshCatMechanisms", version="0.9.0"))
Pkg.add(Pkg.PackageSpec(;name="Plots", version="1.39.0"))
Pkg.add(Pkg.PackageSpec(;name="ProgressBars", version="1.5.1"))
Pkg.add(Pkg.PackageSpec(;name="PyCall", version="1.96.2"))
Pkg.add(Pkg.PackageSpec(;name="Revise", version="3.5.9"))
Pkg.add(Pkg.PackageSpec(;name="RigidBodyDynamics", version="2.4.0"))
Pkg.add(Pkg.PackageSpec(;name="Rotations", version="1.2.0"))
Pkg.add(Pkg.PackageSpec(;name="Smoothers", version="0.1.3"))
Pkg.add(Pkg.PackageSpec(;name="StaticArrays", version="1.7.0"))
Pkg.add(Pkg.PackageSpec(;name="StatsBase", version="0.34.2"))
Pkg.add(Pkg.PackageSpec(;name="StatsPlots", version="0.15.6"))
Pkg.add(Pkg.PackageSpec(;name="Tables", version="1.11.1"))
Pkg.add(Pkg.PackageSpec(;name="YAML", version="0.4.9"))
Pkg.add(Pkg.PackageSpec(;name="LinearAlgebra"))
Pkg.add(Pkg.PackageSpec(;name="Printf"))
Pkg.add(Pkg.PackageSpec(;name="Random"))